{% set name = "aspy.refactor-imports" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: df497c3726ee2931b03d403e58a4590f7f4e60059b115cf5df0e07e70c7c73be

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cached-property

test:
  imports:
    - aspy.refactor_imports

about:
  home: https://github.com/asottile/aspy.refactor_imports
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Utilities for refactoring imports in python-like syntax

extra:
  recipe-maintainers:
    - scopatz
